---
- hosts: apache
  remote_user: centos
  #become: true
  #become_method: sudo
  #become_user: root
  tasks:
   - name: Distribution
     debug: msg="{{ ansible_distribution }}"
   - name: Distribution version
     debug: msg="{{ ansible_distribution_version}}"
     #debug: msg="{{ ansible_distribution_major_version }}"
